include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - generated/**
  strong-mode:
    further-checks: true
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_final_locals: true
    lines_longer_than_80_chars: false
